# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_QCOM_CPR)		+= cpr.o
obj-$(CONFIG_QCOM_CPR_COMMON)	+= cpr-common.o
obj-$(CONFIG_QCOM_CPR3)		+= cpr3.o
obj-$(CONFIG_QCOM_RPMPD)	+= rpmpd.o
obj-$(CONFIG_QCOM_RPMHPD)	+= rpmhpd.o
